---
title: 'Task 1: Principal Component Analysis'
author: "Nick McManus"
date: "2023-02-27"
output: html_document
---

```{r setup, include=TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(ggfortify) # For PCA biplot
```


# Read in and wrangle data:
```{r}
### read in data
usda <- read_csv('usda_nutrients.csv') %>% 
  janitor::clean_names() 

### explore the food group categories (type and number)
# unique(usda$food_group)
usda_types <- usda %>% 
  group_by(food_group) %>% 
  summarize(count = n())

### keep only raw veggies and fruits (no juice) and info on vitamins and minerals
### remove variables representing USRDA
veggies <- usda %>% 
  filter(food_group %in% c("Vegetables and Vegetable Products", "Fruits and Fruit Juices"),
         str_detect(descrip, "raw"),
         !str_detect(descrip, "juice")) %>% 
  select(!ends_with(c("usrda", "_g", "_kcal"))) %>% 
  mutate(food_group = factor(food_group, levels = c('Vegetables and Vegetable Products', 'Fruits and Fruit Juices')))
```

# Run PCA
``` {r}
### run PCA
veggies_pca <- veggies %>%
  select(where(is.numeric)) %>% 
  ## different units, so scale variables
  prcomp(scale = TRUE) 

### See the loadings (weighting for each principal component)
veggies_pca$rotation

### summaries
summary(veggies_pca)
```

# Biplot
```{r}
autoplot(veggies_pca,
     	data = veggies,
     	loadings = TRUE,
     	colour = 'food_group',
     	loadings.label = TRUE,
     	loadings.colour = "black",
     	loadings.label.colour = "black",
     	loadings.label.vjust = -0.5
     	) +
  # scale_color_manual(values = c('red', 'orange', 'yellowgreen', 'darkgreen')) +
  # scale_fill_manual(values = c('red', 'orange', 'yellowgreen', 'darkgreen')) +
  theme_minimal()
```

